const fs = require('fs');
const path = 'C:/Mis_Proyectos(github)/impeccable-minimalist-design/skill/reference/design-frontend-design.md';
let content = fs.readFileSync(path, 'utf8');
content = content.replace(/Resolucin/g, 'Resolución')
                 .replace(/diseo/g, 'diseño')
                 .replace(/ms/g, 'más')
                 .replace(/Diagnstico/g, 'Diagnóstico')
                 .replace(/Ms/g, 'Más')
                 .replace(/mviles/g, 'móviles')
                 .replace(/difciles/g, 'difíciles')
                 .replace(/Optimizacin/g, 'Optimización')
                 .replace(/imgenes/g, 'imágenes')
                 .replace(/compresin/g, 'compresión')
                 .replace(/tamao/g, 'tamaño')
                 .replace(/pequeas/g, 'pequeñas')
                 .replace(/Lgica/g, 'Lógica')
                 .replace(/Gestin/g, 'Gestión')
                 .replace(/catica/g, 'caótica')
                 .replace(/Prdida/g, 'Pérdida')
                 .replace(/sincronizacin/g, 'sincronización')
                 .replace(/navegacin/g, 'navegación')
                 .replace(/disear/g, 'diseñar')
                 .replace(/Accin/g, 'Acción')
                 .replace(/Resolucin/g, 'Resolución')
                 .replace(/Temtica/g, 'Temática')
                 .replace(/Maquetacin/g, 'Maquetación')
                 .replace(/metodologas/g, 'metodologías')
                 .replace(/dinmicas/g, 'dinámicas')
                 .replace(/libreras/g, 'librerías')
                 .replace(/normalizacin/g, 'normalización')
                 .replace(/Disear/g, 'Diseñar')
                 .replace(/semntico/g, 'semántico')
                 .replace(/segn/g, 'según')
                 .replace(/Automtica/g, 'Automática')
                 .replace(/cdigo/g, 'código')
                 .replace(/Automatizacin/g, 'Automatización')
                 .replace(/auditoras/g, 'auditorías')
                 .replace(/automticas/g, 'automáticas')
                 .replace(/Diseo/g, 'Diseño')
                 .replace(/duplicacin/g, 'duplicación')
                 .replace(/errneo/g, 'erróneo');

fs.writeFileSync(path, content, 'utf8');
console.log("Fixed encoding in design-frontend-design.md");
